### ISSUE TITLE
Unable to add  any block in design mode

### ISSUE THREAD

**Issue by xemmex** [parsimony/parsimony#103]
I have just install the Parsimony CMS and everything going well until I hit on a serious bug...
I simply cannot add any block in the page when I am in design mode. I drag the block, it ask me to name it, but nothing appear after I hit on Ok button.

My error log display this : 
[15-Jan-2015 10:14:28 America/Toronto] PHP Fatal error:  Class 'core\blocks\googlemap' not found in /home/parsimony/public_html/modules/admin/module.php on line 118

Have any clues or did I did someting wrong or forgot something ?? :P

**Comment by parsimony** [comment]
Hi,
Sorry it took a while to make this reply.  I've seen your question on github.
It's a very unknown bug. I searched explanations about this bug.

/home/parsimony/public_html/modules/admin/module.php on line 118

Can you add “exit” just before "$tempBlock = new $popBlock($idBlock);"?

protected function addBlockAction($popBlock, $parentBlock, $idBlock, $id_next_block, $stop_typecont, $content, $MODULE, $THEMEMODULE, $THEME) {
$this->initObjects();
$idBlock = strtolower($idBlock);
if($stop_typecont === 'page') { /\* block id in page have to start with a capital */
$idBlock = ucfirst($idBlock);
}
                exit;
...
}

What is the result in the network panel?
You must get something like that:
TOKEN:
6cf4c52c12017d2b963b1cc7de6b002a67d26a47
MODULE:
blog
THEMEMODULE:
blog
THEME:
defaultTheme
DEVICE:
desktop
popBlock:
core\blocks\googlemap
idBlock:
zaezae
id_next_block:
Image
startParentBlock:
parentBlock:
Showcase
start_typecont:
stop_typecont:
page
IDPage:
1
content:

It's surely not an "include" issue or a problem of path. Rather than a PHP issue, I’m tempted to seek the origins javascript side.

Before asking you any other question, can you tell me what browser and version you have?

**Comment by xemmex** [comment]
After review all, I noticed that my Magic_Quote in php.ini was set ON... I just turnit OFF and everything works fine now! :)
