### ISSUE TITLE
Delete a module

### ISSUE THREAD

**Issue by remisarrailh** [parsimony/parsimony#35]
I didn't find a way to delete a module from the back-office.
Did i miss something ?

I manage to do it this way, anyway:
http://parsimonycms.blogspot.fr/2013/01/effacer-un-module.html

**Comment by parsimony** [comment]
Up to now,we believed that creating a module is not a trivial matter.
Create a module is a thoughtful process of development and we prefered to highlight this behavior rather than a compulsive behavior that seeks to create and delete a module on impulse.
That's why it was not a priority, but we are going to implement it very soon ;)

**Comment by parsimony** [comment]
For now, your way is a good way ;)

**Comment by remisarrailh** [comment]
Ok, thanks for the answer, i'll try to avoid creating a lots of modules for no purpose ^^
