### ISSUE TITLE
Multisite

### ISSUE THREAD

**Issue by Tomarnst** [parsimony/parsimony#51]
I just installed parsimony.

When I enable multisite the result is a blank page...
$config['domain']['multisite'] = '1';

When I disable this ...
$config['domain']['multisite'] = '0';

I can navigate to myurl/connect and get login. 

Also I had to set the permissions of all installed folders to 777.

Is it correct that the multisite should be disabled ? and what are the correct permissions for the files and folders?  I'm on a mac osx 1.7.5

Thanks parsimony looks very promising !

**Comment by vkoleman** [comment]
I am also very convinced with Parsimony product but I have the same question with v3.0, running on MacOS 10.7.5

My multisite configuration is $config['domain']['multisite'] = '0';
I can navigate to myurl/connect and get login,
But get a Forbidden when navigating to myurl/,  while I can see the preview when logged in

I ran the following commands to change permissions
before installation:
chmod -R ugo+rwx *.php
chmod -R ug+rwx modules
chmod -R o+rwx modules
chmod -R ug+rwx lib
chmod -R ug+rwx var
chmod -R o+w var
after installation:
chmod -R ugo+rwx profiles

My .htaccess is:
<IfModule mod_rewrite.c>
  RewriteEngine on

  RewriteBase /
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteRule ^(.*)$ index.php?parsiurl=$1 [L,QSA]
</IfModule>
RewriteEngine on

Thanks

**Comment by Tomarnst** [comment]
I'm a little lost here my version is 2.5 where did you get v3.0 ? 
My .htaccess looks almost the same:

Options +FollowSymLinks
RewriteEngine on
RewriteBase /
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^(.*)$ index.php?parsiurl=$1 [L,QSA]

**Comment by vkoleman** [comment]
sorry, it is the future RC 3.0 available here https://github.com/parsimony/parsimony_cms/

**Comment by Tomarnst** [comment]
I shall install that one first ... and see if the issue still exists on my install

**Comment by remisarrailh** [comment]
> But get a Forbidden when navigating to myurl/, while I can see the preview when logged in

By default, anonymous user don't have the right to see the website , you can activate this by modifying the permissions in 
_Accounts --> Permissions --> Anonymous --> Module (Blog) --> Enable the Blog module for Anonymous Role_

![permissions](https://f.cloud.github.com/assets/2841495/560177/b0e1b120-c46b-11e2-9748-ceea296016b9.png)

(I documented this in french here)
http://parsimonycms.blogspot.fr/2013/05/forbidden-dans-la-page-daccueil.html

This behaviour is coded here:
 https://github.com/parsimony/parsimony_cms/blob/master/modules/core/classes/request.php#L274

**Comment by vkoleman** [comment]
Yes,  it fixed my problem, I should have checked your blog .
Thanks a lot

**Comment by Tomarnst** [comment]
Installed the version 3.0 as suggested by vkoleman, left the .htaccess from my first attempt had to give 777 permissions to all the files/folders except the lib folder.

This worked...! also setting the multisite to : $config['domain']['multisite'] = '1';
Although i'm not sure how to setup a second site, maybe someone can give me a pointer on this.

Thanks again.

**Comment by remisarrailh** [comment]
OK, i managed to partially understand how the multisite mode work.
Anyway i didn't really test this solution and you should wait for a proper explanation of the creator of Parsimony has I had some really bad issues with it.

Lets say your website is example.org
You want to make multiples sites like this:
- site1.example.org (another site)
- site2.example.org (another site)
- example.org or www.example.org (the main site)

# Requirements
- DNS server that will resolve the domain/subdomain names on the client.
- You could also modified your client hosts file

# SLD configuration

First check in the configuration the _$config['domain']['sld']_
With our example it should be set to 2 : example.org (because example-1 org-2)
If your main domain is this.is.an.example.org then it will be 5 : (this-1 is-2 an-3 example-4 org-5)

This is important has when you activate multisite, parsimony will checked the last level to identified subdomain.

Then in your DNS configuration , all the subdomains must point on the main domain
On a DNS server you should add this
`site1  IN CNAME example.org`
On a hosts file you should add this
`IP_ADDRESS site1.example.org`
(Where IP_ADDRESS is the IP address of the webserver, 127.0.0.1 if it is local)

# Activate Multisite

First, you have to put this in config.php
`$config['domain']['multisite'] = '1';`

AND you have to copy the file in
- /profiles/www
- /var/backup/www
- /var/sessions/www

in a directory with the name of the subdomain

![image](https://f.cloud.github.com/assets/2841495/560686/15280502-c47c-11e2-969a-ac9ad1ae12d1.png)

# Test

Let's go in example.org/connect
You should see a flag after Parsimony Beta

![image](https://f.cloud.github.com/assets/2841495/560704/f93bb522-c47c-11e2-8f25-f568f5b720bb.png)

This will simply redirected you to site1.example.org or site2.example.org

You should be able to modify/add/delete every subdomain block without modifying the other subdomain.

# Bug

## config.php

I don't know why (this is surely because I didn't do it right)

But I had this error:
![image](https://f.cloud.github.com/assets/2841495/560731/fc961a7c-c47d-11e2-84a9-76bab54d9f47.png)

It resolved by copying config.php in /profiles/site1 and /profiles/site2

## Can't erase block anymore :-(

I have yet to resolve this, i can't delete anymore blocks (but still can create some)
![image](https://f.cloud.github.com/assets/2841495/560742/693a6336-c47e-11e2-883e-db94f20d288e.png)

**Comment by Tomarnst** [comment]
Well I tried this but the result is that I can't edit any page (won't save) anymore... 
I did set the $config['domain']['multisite'] = '0'; (back to 0) removed all the multisite files (site1,2) but still not able to edit any pages. This made me looking at the permissions settings but here same problem Parsimony won't save the changes I made on the settings. Tried to set all the files and folders to 777  and deleted the cache without any results.....

**Comment by parsimony** [comment]
Hi,

To add a profile and map it with a domain you must to follow @maditnerd explanations :+1: 

It's just a little bit more simple for the init of the profile : 
- copy /profiles/www in /profiles/newprofile
- copy /config.php into /profiles/newprofile ( you can change database configs if you want to play we with a new dataset.)

We plan to do an article in the doc, and add an interface in Parsimony admin to automate the process.

For the bug for save blocks and pages, it seems to be a bug in 3.0 RC, we will fix it early this week.
